---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: schabiyo/ossdemo
    tag: latest

params:
  service_principal_id:
  service_principal_secret:
  tenant_id:
  subscription_id:
  paas_rg:
  server_prefix:
  acr_endpoint:
  acr_username:
  acr_password:
  


inputs:
  - name: api-nodejs
  - name: api-version
run:
  path: api-nodejs/ci/tasks/deploy-to-prod-k8s.sh
